apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app-image-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flask-app-image
        version: "v1"
        slot: blue

    spec:
      containers: 
        - name: flask-app-image
          image: docker.io/manukoli1986/flask-app-image:v1
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
